load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "presage_android_aar",
    calculators = ["//mediapipe/examples/ios/presage_graph_mpiris/graph:client_gpu_graph_deps"],
)
